server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb+srv://anhminh270622:anhminh270622@daily-chatbot.8bmzl6e.mongodb.net/daily-chatbot?retryWrites=true&w=majority&appName=daily-chatbot
debug: true
